# Generated by Django 2.2.24 on 2021-08-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDriveLogParsingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('buses_count', models.PositiveIntegerField()),
                ('runs_count', models.PositiveIntegerField()),
                ('time_spent', models.PositiveIntegerField()),
                ('exception_bus_count', models.PositiveIntegerField()),
                ('error_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExceptionParsingBus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('carno', models.CharField(max_length=15)),
            ],
        ),
    ]
