# Generated by Django 2.2.24 on 2021-08-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydrivelogparsingstatus',
            name='stoptostop_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
