# Generated by Django 2.2.24 on 2021-08-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dailydrivelogparsingstatus_stoptostop_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineNotifyControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=50)),
                ('activate', models.BooleanField(default=True)),
            ],
        ),
    ]
