# Generated by Django 2.2.24 on 2021-08-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dailydrivelogparsingstatus_time_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydrivelogparsingstatus',
            name='time_spent',
            field=models.PositiveIntegerField(),
        ),
    ]
