# Generated by Django 2.2.24 on 2021-08-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210804_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailydrivelogparsingstatus',
            name='error_bus_count',
        ),
        migrations.AddField(
            model_name='dailydrivelogparsingstatus',
            name='exception_bus_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailydrivelogparsingstatus',
            name='runs_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
