# Generated by Django 2.2.24 on 2021-08-20 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_linenotifycontrol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LineNotifyControl',
        ),
    ]
