# Generated by Django 2.2.24 on 2021-09-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDataTrafficParsingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_spent', models.PositiveIntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
